In [98]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
df = pd.read_csv('q_raw.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29033 entries, 0 to 29032
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   q_id             29033 non-null  object
 1   q_status         28982 non-null  object
 2   q_date           28857 non-null  object
 3   q_year           28871 non-null  float64
 4   ia_date          2099 non-null   object
 5   wd_date          8934 non-null   object
 6   on_date          2328 non-null   object
 7   entity           29033 non-null  object
 8   project_name     9553 non-null   object
 9   developer        4378 non-null   object
 10  utility          24970 non-null  object
 11  county_1         28119 non-null  object
 12  county_2         78 non-null     object
 13  county_3         13 non-null     object
 14  state            28079 non-null  object
 15  region           29032 non-null  object
 16  service          22879 non-null  object
 17  poi_name         27766 non-null  object
 18  prop_date        25750 non-null  object
 19  prop_year        25074 non-null  float64
 20  ia_status_raw    24934 non-null  object
 21  ia_status_clean  28977 non-null  object
 22  type_clean       29033 non-null  object
 23  type1            29014 non-null  object
 24  type2            3259 non-null   object
 25  type3            66 non-null     object
 26  mw1              28517 non-null  float64
 27  mw2              1161 non-null   float64
 28  mw3              32 non-null     float64
dtypes: float64(5), object(24)
memory usage: 6.4+ MB

In [100]:
df.head(10)

,q_id,q_status,q_date,q_year,ia_date,wd_date,on_date,entity,project_name,developer,...,prop_year,ia_status_raw,ia_status_clean,type_clean,type1,type2,type3,mw1,mw2,mw3
0,GIA-97,withdrawn,1/7/2022,2022.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2024.0,Withdrawn,Withdrawn,Solar,Solar,NaN,NaN,350.0,NaN,NaN
1,GIA-40,active,10/24/2009,2009.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2011.0,Upgrade Approved,IA Executed,Coal,Coal,NaN,NaN,20.0,NaN,NaN
2,GIA-41,active,10/24/2009,2009.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2012.0,Upgrade Approved,IA Executed,Coal,Coal,NaN,NaN,17.0,NaN,NaN
3,GIA-73,withdrawn,11/19/2018,2018.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2021.0,Withdrawn,Withdrawn,Solar,Solar,NaN,NaN,300.0,NaN,NaN
4,GIA-96,active,10/22/2021,2021.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2023.0,FS,Facilities Study,Wind,Wind,NaN,NaN,98.0,NaN,NaN
5,GIA-77,active,1/18/2019,2019.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2019.0,GIA,IA Executed,Gas,Gas,NaN,NaN,50.0,NaN,NaN
6,GIA-62,withdrawn,10/12/2017,2017.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2020.0,Withdrawn,Withdrawn,Solar,Solar,NaN,NaN,202.0,NaN,NaN
7,GIA-83,active,6/19/2019,2019.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2025.0,GIA,IA Executed,Wind,Wind,NaN,NaN,1018.0,NaN,NaN
8,GIA-69,withdrawn,5/31/2018,2018.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2020.0,Withdrawn,Withdrawn,Solar,Solar,NaN,NaN,105.0,NaN,NaN
9,GIA-71,withdrawn,12/6/2018,2018.0,NaN,NaN,NaN,AEC,NaN,NaN,...,2021.0,Withdrawn,Withdrawn,Solar,Solar,NaN,NaN,250.0,NaN,NaN

In [101]:
encoded_df = pd.read_csv('q_data_encoded.csv')
encoded_df.head(10)

C:\Users\celin\AppData\Local\Temp\ipykernel_14856\3254982332.py:1: DtypeWarning: Columns (4,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  encoded_df = pd.read_csv('q_data_encoded.csv')

,q_id,q_date,q_year,ia_date,wd_date,on_date,project_name,developer,utility,county_1,...,type1Waste.Heat,type1Wind,type1Wood,type2Battery,type2Gas,type2Other,type2Solar,type2Wind,type3Battery,type3Solar
0,GIA-97,1/7/2022,2022.0,NaN,NaN,NaN,NaN,NaN,AEC,new madrid,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GIA-40,10/24/2009,2009.0,NaN,NaN,NaN,NaN,NaN,AEC,new madrid,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GIA-41,10/24/2009,2009.0,NaN,NaN,NaN,NaN,NaN,AEC,randolph,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GIA-73,11/19/2018,2018.0,NaN,NaN,NaN,NaN,NaN,AEC,pemiscot,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GIA-96,10/22/2021,2021.0,NaN,NaN,NaN,NaN,NaN,AEC,lincoln,...,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,GIA-77,1/18/2019,2019.0,NaN,NaN,NaN,NaN,NaN,AEC,mayes,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,GIA-62,10/12/2017,2017.0,NaN,NaN,NaN,NaN,NaN,AEC,new madrid,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,GIA-83,6/19/2019,2019.0,NaN,NaN,NaN,NaN,NaN,AEC,randolph,...,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GIA-69,5/31/2018,2018.0,NaN,NaN,NaN,NaN,NaN,AEC,kingfisher,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,GIA-71,12/6/2018,2018.0,NaN,NaN,NaN,NaN,NaN,AEC,new madrid,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
columns_to_keep = ['q_date', 'q_year', 'prop_year', 'ia_status_raw', 'region','state', 'type1','mw1', 'mw2', 'mw3']
df_dropped = df[columns_to_keep].copy()

In [103]:
# categorical = ["state", "region", "type1"]
value_counts_region = df_dropped['region'].value_counts().head(10)
print(value_counts_region)

region
PJM                    7738
West (non-ISO)         6610
MISO                   4071
Southeast (non-ISO)    3070
CAISO                  2274
ERCOT                  1952
NYISO                  1260
ISO-NE                 1255
SPP                     802
Name: count, dtype: int64

In [104]:
# One-hot encode the new column
encoded_categories = pd.get_dummies(df_dropped['region'], prefix='region').astype(int)

# Concatenate the one-hot encoded columns with the original DataFrame
df_with_region = pd.concat([df_dropped, encoded_categories], axis=1)
df_with_region.head(10)

,q_date,q_year,prop_year,ia_status_raw,region,state,type1,mw1,mw2,mw3,region_CAISO,region_ERCOT,region_ISO-NE,region_MISO,region_NYISO,region_PJM,region_SPP,region_Southeast (non-ISO),region_West (non-ISO)
0,1/7/2022,2022.0,2024.0,Withdrawn,Southeast (non-ISO),MO,Solar,350.0,NaN,NaN,0,0,0,0,0,0,0,1,0
1,10/24/2009,2009.0,2011.0,Upgrade Approved,Southeast (non-ISO),MO,Coal,20.0,NaN,NaN,0,0,0,0,0,0,0,1,0
2,10/24/2009,2009.0,2012.0,Upgrade Approved,Southeast (non-ISO),MO,Coal,17.0,NaN,NaN,0,0,0,0,0,0,0,1,0
3,11/19/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,300.0,NaN,NaN,0,0,0,0,0,0,0,1,0
4,10/22/2021,2021.0,2023.0,FS,Southeast (non-ISO),OK,Wind,98.0,NaN,NaN,0,0,0,0,0,0,0,1,0
5,1/18/2019,2019.0,2019.0,GIA,Southeast (non-ISO),OK,Gas,50.0,NaN,NaN,0,0,0,0,0,0,0,1,0
6,10/12/2017,2017.0,2020.0,Withdrawn,Southeast (non-ISO),MO,Solar,202.0,NaN,NaN,0,0,0,0,0,0,0,1,0
7,6/19/2019,2019.0,2025.0,GIA,Southeast (non-ISO),MO,Wind,1018.0,NaN,NaN,0,0,0,0,0,0,0,1,0
8,5/31/2018,2018.0,2020.0,Withdrawn,Southeast (non-ISO),OK,Solar,105.0,NaN,NaN,0,0,0,0,0,0,0,1,0
9,12/6/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,250.0,NaN,NaN,0,0,0,0,0,0,0,1,0

In [105]:
df_with_region['ia_status_category'] = df_with_region['ia_status_raw'].replace({
    'System Impact Study': 'System Impact Study',
    'IA Executed': 'IA Executed',
    'Executed': 'IA Executed',
    'Withdrawn': 'Withdrawn',
    'Feasibility Study': 'Feasibility Study',
    'Feasibility': 'Feasibility Study',
    'In progress': 'In progress',
    'Active': 'Operational',
    'Operational': 'Operational',
    'operational': 'Operational',
    'Facility Study': 'Facility Study'
})

df_revised = df_with_region[df_with_region['ia_status_category'].isin([
    'System Impact Study',
    'IA Executed',
    'Withdrawn',
    'Feasibility Study',
    'In progress',
    'Operational',
    'Facility Study'
])]

df_revised.head(10)

,q_date,q_year,prop_year,ia_status_raw,region,state,type1,mw1,mw2,mw3,region_CAISO,region_ERCOT,region_ISO-NE,region_MISO,region_NYISO,region_PJM,region_SPP,region_Southeast (non-ISO),region_West (non-ISO),ia_status_category
0,1/7/2022,2022.0,2024.0,Withdrawn,Southeast (non-ISO),MO,Solar,350.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
3,11/19/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,300.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
6,10/12/2017,2017.0,2020.0,Withdrawn,Southeast (non-ISO),MO,Solar,202.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
8,5/31/2018,2018.0,2020.0,Withdrawn,Southeast (non-ISO),OK,Solar,105.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
9,12/6/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,250.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
10,5/31/2016,2016.0,2018.0,Withdrawn,Southeast (non-ISO),OK,Wind,200.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
14,5/23/2019,2019.0,2022.0,Withdrawn,Southeast (non-ISO),OK,Solar,99.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
15,9/3/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Wind,170.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
16,12/1/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Solar,225.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn
18,1/22/2019,2019.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Wind,250.0,NaN,NaN,0,0,0,0,0,0,0,1,0,Withdrawn

In [106]:
columns_to_sum = ['mw1', 'mw2', 'mw3']
df_revised['total_mw'] = df_revised[columns_to_sum].sum(axis=1, skipna=True)
df_cleaner = df_revised.copy().drop(columns=['mw1', 'mw2','mw3']).dropna()
df_cleaner.head(10)

C:\Users\celin\AppData\Local\Temp\ipykernel_14856\329816572.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_revised['total_mw'] = df_revised[columns_to_sum].sum(axis=1, skipna=True)

,q_date,q_year,prop_year,ia_status_raw,region,state,type1,region_CAISO,region_ERCOT,region_ISO-NE,region_MISO,region_NYISO,region_PJM,region_SPP,region_Southeast (non-ISO),region_West (non-ISO),ia_status_category,total_mw
0,1/7/2022,2022.0,2024.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,350.0
3,11/19/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,300.0
6,10/12/2017,2017.0,2020.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,202.0
8,5/31/2018,2018.0,2020.0,Withdrawn,Southeast (non-ISO),OK,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,105.0
9,12/6/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,250.0
10,5/31/2016,2016.0,2018.0,Withdrawn,Southeast (non-ISO),OK,Wind,0,0,0,0,0,0,0,1,0,Withdrawn,200.0
14,5/23/2019,2019.0,2022.0,Withdrawn,Southeast (non-ISO),OK,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,99.0
15,9/3/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Wind,0,0,0,0,0,0,0,1,0,Withdrawn,170.0
16,12/1/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,0,0,0,0,1,0,Withdrawn,225.0
18,1/22/2019,2019.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Wind,0,0,0,0,0,0,0,1,0,Withdrawn,250.0

In [107]:
types = pd.get_dummies(df_cleaner['type1'], prefix='type1').astype(int)

# Concatenate the one-hot encoded columns with the original DataFrame
df_cleaned = pd.concat([df_cleaner,types], axis=1)
df_cleaned.head(10)

,q_date,q_year,prop_year,ia_status_raw,region,state,type1,region_CAISO,region_ERCOT,region_ISO-NE,...,type1_Oil,type1_Other,type1_Other Storage,type1_Pumped Storage,type1_Solar,type1_Steam,type1_Unknown,type1_Waste Heat,type1_Wind,type1_Wood
0,1/7/2022,2022.0,2024.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,11/19/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
6,10/12/2017,2017.0,2020.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,5/31/2018,2018.0,2020.0,Withdrawn,Southeast (non-ISO),OK,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9,12/6/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
10,5/31/2016,2016.0,2018.0,Withdrawn,Southeast (non-ISO),OK,Wind,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,5/23/2019,2019.0,2022.0,Withdrawn,Southeast (non-ISO),OK,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,9/3/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Wind,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,12/1/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,1,0,0,0,0,0
18,1/22/2019,2019.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Wind,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [108]:
types = pd.get_dummies(df_cleaned['ia_status_category'], prefix='ia_status').astype(int)

# Concatenate the one-hot encoded columns with the original DataFrame
df_final_dropped= pd.concat([df_cleaned,types], axis=1)
df_final_dropped.head(10)

,q_date,q_year,prop_year,ia_status_raw,region,state,type1,region_CAISO,region_ERCOT,region_ISO-NE,...,type1_Unknown,type1_Waste Heat,type1_Wind,type1_Wood,ia_status_Facility Study,ia_status_Feasibility Study,ia_status_IA Executed,ia_status_Operational,ia_status_System Impact Study,ia_status_Withdrawn
0,1/7/2022,2022.0,2024.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,11/19/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,10/12/2017,2017.0,2020.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,5/31/2018,2018.0,2020.0,Withdrawn,Southeast (non-ISO),OK,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,12/6/2018,2018.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,5/31/2016,2016.0,2018.0,Withdrawn,Southeast (non-ISO),OK,Wind,0,0,0,...,0,0,1,0,0,0,0,0,0,1
14,5/23/2019,2019.0,2022.0,Withdrawn,Southeast (non-ISO),OK,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,9/3/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Wind,0,0,0,...,0,0,1,0,0,0,0,0,0,1
16,12/1/2020,2020.0,2023.0,Withdrawn,Southeast (non-ISO),MO,Solar,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,1/22/2019,2019.0,2021.0,Withdrawn,Southeast (non-ISO),MO,Wind,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [109]:
df_final_dropped = df_final_dropped.drop(columns=['q_date', 'q_year',	'prop_year', 'ia_status_raw','ia_status_category', 'region', 'state', 'type1','ia_status_Facility Study',
       'ia_status_Feasibility Study', 'ia_status_IA Executed',
       'ia_status_Operational', 'ia_status_System Impact Study'])
# df_final_dropped = df_cleaned.drop(columns=['q_date', 'q_year',	'prop_year', 'ia_status_raw', 'region', 'state', 'type1'])
# df_final_dropped.head(10)

In [114]:
df_final_dropped.columns

Index(['region_CAISO', 'region_ERCOT', 'region_ISO-NE', 'region_MISO',
       'region_NYISO', 'region_PJM', 'region_SPP',
       'region_Southeast (non-ISO)', 'region_West (non-ISO)', 'total_mw',
       'type1_Battery', 'type1_Biofuel', 'type1_Biogas', 'type1_Biomass',
       'type1_Coal', 'type1_Diesel', 'type1_Flywheel', 'type1_Fuel Cell',
       'type1_Gas', 'type1_Geothermal', 'type1_Gravity Rail', 'type1_Hybrid',
       'type1_Hydro', 'type1_Landfill', 'type1_Methane', 'type1_Nuclear',
       'type1_Offshore Wind', 'type1_Oil', 'type1_Pumped Storage',
       'type1_Solar', 'type1_Steam', 'type1_Waste Heat', 'type1_Wind',
       'type1_Wood', 'ia_status_Withdrawn'],
      dtype='object')

In [112]:
df_final_dropped = df_final_dropped.drop(columns=['type1_Unknown', 'type1_Other', 'type1_Other Storage'])

In [113]:
df_final_dropped.to_csv('q_data_cleaned.csv')